cf_labs_git: https://github.com/opsforge/cf-labs.git
cf_labs_git_branch: master

region: eu-west-1
s3_bucket: TERRAFORM_S3_BUCKET_NAME
s3_regexp: (.*).tfstate

# Keep commented out below if using -v arguments to pass to fly (avoiding accidental git commits)
aws_tf_access_key: MYMAGICKEY
aws_tf_secret_key: MYMAGICSECRET

ec2_instance_key: 'MYPUBLIC_KEY'
